name: "auto assign"
on:
  pull_request:
    types: [assigned]

jobs:
  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        config: '.github/auto-assigner.yml'
        token: ${{ secrets.GITHUB_TOKEN }}
